title: Time Team Episode Database
email: "yannick.signer@gmail.com"
description: >-
  Database of episodes of the Time Team television series, providing access to excavation reports, HER entries and further information regarding the conducted archaeological work.

repository: "yannicksigner/time-team-database/"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh

google_spreadsheet: https://docs.google.com/spreadsheets/d/13tlJfWIflEA2xGpRRfYw1xoQcGypCpukEkqpt4XYaEY
